#!/bin/bash
# Needs package jq: https://jqlang.github.io/jq/
if [ -z "$1" ]
then
    echo "Usage: dbsig <0x1234567890abcdef>"
    exit 0
fi

# Making curl request
result_json=`curl -s "https://api.openchain.xyz/signature-database/v1/lookup?filter=false&event=$1" \
  -H 'authority: api.openchain.xyz' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9,es-ES;q=0.8,es;q=0.7,fr;q=0.6' \
  -H 'origin: https://openchain.xyz' \
  -H 'referer: https://openchain.xyz/' \
  -H 'sec-ch-ua: "Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36' \
  --compressed 2>/dev/null`

event=`echo $result_json | jq .result.event | jq .[] | jq .[0].name | tr -d '"'`
echo $event
